### ISSUE TITLE
Memory callback functions accept user argument

### ISSUE THREAD

**Issue by tonysparks** [kgabis/ape#6]
Hello,

It would be great if the API for memory handling functions allowed for a user supplied argument -- which is useful for allocators that are not global.

```c
typedef void*        (*ape_malloc_fn)(size_t size, void* mallocArg);
typedef void         (*ape_free_fn)(void *ptr, void* freeArg);

void ape_set_memory_functions(void* mallocArg, ape_malloc_fn malloc_fn, void* freeArg, ape_free_fn free_fn);

// user land code:
struct Allocator {
...
}

struct Program {
    struct Allocator* alloc;
} * program;

void* myMalloc(size_t size, void* arg) {
   struct Allocator* allocator = (struct Allocator*) arg; // allows to specify an allocator without being a global
   ...
}

...
ape_set_memory_functions(program.alloc, &myAlloc, program.alloc, &myFree);

```

**Comment by kgabis** [comment]
Eventually I want to have per-ape memory functions, global allocators are a bit of a temporary measure. Until then can't you wrap your allocation functions? Or am I missing something?
```c
static struct Allocator *s_allocator;

static void* malloc_wrapper(size_t size) {
    return allocator_malloc(s_allocator, size);
}

static void free_wrapper(void *ptr) {
    allocator_free(s_allocator, ptr);
}

int main(...) {
    ape_set_memory_functions(malloc_wrapper, free_wrapper);
}
```

**Comment by tonysparks** [comment]
That still assumes a global Allocator that can be accessed via the malloc_wrapper - which is what I'd like to avoid.

Perhaps better illustrated:

```c

static void* malloc_wrapper(size_t size) {
    return allocator_malloc(s_allocator, size); // how does this access s_allocator without it being a global
}

static void free_wrapper(void *ptr) {
    allocator_free(s_allocator, ptr);
}

int main(...) {
    struct Allocator *s_allocator; // created here, i.e., not a global
    ape_set_memory_functions(malloc_wrapper, free_wrapper);
}
```

**Comment by kgabis** [comment]
ape_malloc and ape_free are global so having allocator global on user side is no different than having it global within the library.
```c
struct Allocator *s_allocator;

static void* malloc_wrapper(size_t size) {
    return allocator_malloc(s_allocator, size);
}

static void free_wrapper(void *ptr) {
    allocator_free(s_allocator, ptr);
}

int main(...) {
    s_allocator = allocator_make();
    ape_set_memory_functions(malloc_wrapper, free_wrapper);
}
```

**Comment by tonysparks** [comment]
Sorry, I completely glossed over the statement: `Eventually I want to have per-ape memory functions, global allocators are a bit of a temporary measure.`

Sounds good to me -- looking forward to per-instance memory functions.

Thanks!

**Comment by kgabis** [comment]
Global allocation functions are no longer a thing, in 0.9.0 (https://github.com/kgabis/ape/commit/df4b7d4220a72eedac8e9d57942422da82b8baf4) I've added ```ape_make_ex(...)``` that accepts custom allocation functions and a context that will be used for all subsequent allocations.
