### ISSUE TITLE
Problem with recusive

### ISSUE THREAD

**Issue by haifenghuang** [kgabis/ape#7]
In the `Ape Playgound` website, the recursion example runs fine, but when I change the recusion number to 29 (or above 29), It report errors, below is the image:
![image](https://user-images.githubusercontent.com/4425219/115666389-1c875900-a377-11eb-84ec-8d085ccfc7c6.png)

**Comment by kgabis** [comment]
There's a 500ms timeout to avoid hanging your browser, it's working as intended.
